kind: Deployment
apiVersion: apps/v1
metadata:
  name: banking-app
  namespace: dpg-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        app: banking-app
    spec:
      containers:
        - name: banking-app-api
          image: ciphertrust/cdsp.cookbook.samples:bank_app_api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
        - name: banking-app-ui
          image: ciphertrust/cdsp.cookbook.samples:bank_app_ui
          imagePullPolicy: Always
          env:
            - name: API_IP
              value: "192.168.2.190"
            - name: API_PORT
              value: "31002"
          ports:
            - containerPort: 3000
        - image: thalesciphertrust/ciphertrust-data-protection-gateway:1.1.0
          imagePullPolicy: IfNotPresent
          name: dpg-container
          env:
           - name: KMS
             value: "192.168.2.187"
           - name: REG_TOKEN
             value: "U5nSmUfkn2BXBYaFtpiwRTk24IJoSrRTydXi0ENLwXudlTywL8FaWQO01BhYCdkC"
           - name: DESTINATION_URL
             value: "http://192.168.2.190:31000"
           - name: DPG_PORT
             value: '9005'
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: banking-app
  namespace: dpg-bank
spec:
  type: NodePort
  ports:
    - name: api
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31000
    - name: ui
      port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 31001
    - name: dpg
      port: 9005
      targetPort: 9005
      nodePort: 31002
  selector:
    app: banking-app

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: dpg-configmap
  namespace: dpg-bank
data:
    TLS_ENABLED: 'false'
    KMS: "192.168.2.187"
    REG_TOKEN: "U5nSmUfkn2BXBYaFtpiwRTk24IJoSrRTydXi0ENLwXudlTywL8FaWQO01BhYCdkC"
    DESTINATION_URL: "http://192.168.2.190:31000"
    DPG_PORT: '9005'