kind: Deployment
apiVersion: apps/v1
metadata:
  name: banking-app
  namespace: dpg-bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banking-app
  template:
    metadata:
      labels:
        app: banking-app
    spec:
      containers:
        - name: banking-app-api
          image: ciphertrust/cdsp.cookbook.samples:bank_app_api
          imagePullPolicy: Always
          ports:
            - containerPort: 8080        
        - name: banking-app-ui
          image: ciphertrust/cdsp.cookbook.samples:bank_app_ui
          imagePullPolicy: Always
          env:
            - name: API_IP
              value: "192.168.2.190"
            - name: API_PORT
              value: "9005"
          ports:
            - containerPort: 3000
        - image: thalesciphertrust/ciphertrust-data-protection-gateway:1.1.0
          imagePullPolicy: IfNotPresent
          name: dpg-container
          env:
           - name: KMS
             value: 192.168.2.187
           - name: REG_TOKEN
             value: K8YalPQNhQz45ncu8db7nQSAUDsBR3EGiijmzrT7Kb0zLxuwN1Ithaapj5HoyNjS
           - name: DESTINATION_URL
             value: http://192.168.2.190:31000
           - name: DPG_PORT
             value: 9005
           - name: TLS_ENABLED
             value: false
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: banking-app
  namespace: dpg-bank
spec:
  type: NodePort
  ports:
    - name: api
      port: 8080
      targetPort: 8080
      protocol: TCP
      nodePort: 31000
    - name: ui
      port: 3000
      targetPort: 3000
      protocol: TCP
      nodePort: 31001
  selector:
    app: banking-app