cm_ip: 192.168.2.187
cm_private_ip: 1.1.1.1
cm_username: admin
cm_password: ChangeIt01!
cm_tenant_id:

this_node_connection_string:
  server_ip: "{{ cm_ip }}"
  server_private_ip: "{{ cm_private_ip }}"
  server_port: 5432
  user: "{{ cm_username }}"
  password: "{{ cm_password }}"
  auth_domain_path: "{{ cm_tenant_id }}"
  verify: False

cm_local_ca_id: "9de069b9-fb61-4ba3-a27c-329ed25b8e3c"
kubernetes_server_ip: 192.168.2.190
dpg_key_name: HIPAAKey
char_set_name: HIPAACharSet
protection_policy: HIPAAProtPolicy
patients_userset: Patients
nurses_userset: Practitioners
access_policy: HIPAAAccessPolicy
dpg_policy_name: HIPAADpgPolicy
client_profile_name: HIPAAClientProfile
nae_port_number: 9006
ca_id: "kylo:kylo:naboo:localca:{{ cm_local_ca_id }}"
ca_uuid: "{{ cm_local_ca_id }}"
API_SERVER_IP: "{{ kubernetes_server_ip }}"
API_SERVER_PORT: 31002
KMS_IP: "{{ cm_ip }}"
DPG_PORT: 9006
DESTINATION_URL: "http://{{ kubernetes_server_ip }}:31000"
STRAPI_HOST: 192.168.2.190
